ROLLBACK;
BEGIN;

CREATE DOMAIN ID as VARCHAR(200);
CREATE DOMAIN SHORT_TEXT as VARCHAR(255);

CREATE TABLE IF NOT EXISTS users(
    name SHORT_TEXT NOT NULL,
    email SHORT_TEXT UNIQUE NOT NULL,
    password_hash SHORT_TEXT NOT NULL,
    confirmed BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS email_confirmation_codes(
    email SHORT_TEXT PRIMARY KEY,
    code CHAR(7) NOT NULL,
    created_at BIGINT NOT NULL,
    expires_at BIGINT NOT NULL
);

COMMIT;